### ISSUE TITLE
Include URL in copied score

### ISSUE THREAD

**Issue by SeanMcP** [cassidoo/jumblie#2]
https://github.com/cassidoo/jumblie/blob/1f842b8f64a13e6c5658f6a4f2de49c35ae453d5/game.js#L300

Maybe something like:

```js
navigator.clipboard.writeText(scoreString + "\nhttps://jumblie.com")
```

Wordle _doesn't_ do this, but most people probably know what Wordle is and how to find it. For a new game, having a link seems reasonable.

**Comment by SeanMcP** [comment]
Ooo, the OG image is a good point. Maybe leave as is and wait for search engines to catch up.

**Comment by cassidoo** [comment]
I ended up adding it! People can delete it if they don't want it 😆❤️
