### ISSUE TITLE
Loading partially solved games and then giving up results in already guessed answers showing twice

### ISSUE THREAD

**Issue by mattschlosser** [cassidoo/jumblie#6]
<details>
<summary>
Screenshot: Warning: Spoilers
</summary>
<img src="https://github.com/cassidoo/jumblie/assets/8870594/731ef166-e714-42b6-9b03-34a3f333352e">

</details>

If you refresh the page after already solving some of the answers, and then proceed to give up, the answers you already found will be shown twice.

**Comment by cassidoo** [comment]
Just fixed this! Thank you!
